// <auto-generated />
namespace CircuitBentCMS.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class PageWidgetAreasAdded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PageWidgetAreasAdded));
        
        string IMigrationMetadata.Id
        {
            get { return "201311290849046_PageWidgetAreasAdded"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
