// <auto-generated />
namespace CircuitBentCMS.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class StoreSettingsRemovedImageSliders : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(StoreSettingsRemovedImageSliders));
        
        string IMigrationMetadata.Id
        {
            get { return "201310270956351_StoreSettingsRemovedImageSliders"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
