// <auto-generated />
namespace CircuitBentCMS.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class ImageGalleryDescriptionRenamed : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ImageGalleryDescriptionRenamed));
        
        string IMigrationMetadata.Id
        {
            get { return "201310020745392_ImageGalleryDescriptionRenamed"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
