// <auto-generated />
namespace CircuitBentCMS.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class ImageSliderTransitionModeAdded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ImageSliderTransitionModeAdded));
        
        string IMigrationMetadata.Id
        {
            get { return "201311061054454_ImageSliderTransitionModeAdded"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
