// <auto-generated />
namespace CircuitBentCMS.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddedScriptsToPage : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddedScriptsToPage));
        
        string IMigrationMetadata.Id
        {
            get { return "201310121826222_AddedScriptsToPage"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
