// <auto-generated />
namespace CircuitBentCMS.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class StoreSettingsAdded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(StoreSettingsAdded));
        
        string IMigrationMetadata.Id
        {
            get { return "201310241809131_StoreSettingsAdded"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
